export const bike = [
    {
        id: "e43638ce-6aa0-4b85-b27f-e1d07eb678c6",
        name: 'Raju',
        age: 23,
        ownerImage: 'images/vehicle-owners/1.jpg',
        experience: '3 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹40/5km',
        vehicleType: 'bike',
        vehicleName: 'bajaj',
        vehicleImage: 'images/vehicles/bike/bajaj-ct100b.jpg',
        rating: 'images/ratings/rating-35.png'
    },
    {
        id: "15b6fc6f-327a-4ec4-896f-486349e85a3d",
        name: 'ram',
        age: 23,
        ownerImage: 'images/vehicle-owners/bike/1.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹40/5km',
        vehicleType: 'bike',
        vehicleName: 'bajaj',
        vehicleImage: 'images/vehicles/bike/bajaj-platina-100e.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "83d4ca15-0f35-48f5-b7a3-1ea210004f2e",
        name: 'gopal',
        age: 25,
        ownerImage: 'images/vehicle-owners/bike/2.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹40/5km',
        vehicleType: 'bike',
        vehicleName: 'bajaj',
        vehicleImage: 'images/vehicles/bike/bajaj-platina-100e.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "54e0eccd-8f36-462b-b68a-8182611d9add",
        name: 'ravi',
        age: 25,
        ownerImage: 'images/vehicle-owners/bike/3.jpg',
        experience: '0 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹30/5km',
        vehicleType: 'bike',
        vehicleName: 'hero',
        vehicleImage: 'images/vehicles/bike/Hero Pleasure Plus Xtec.jpg',
        rating: 'images/ratings/rating-0.png'
    },
    {
        id: "3ebe75dc-64d2-4137-8860-1f5a963e534b",
        name: 'sameer',
        age: 20,
        ownerImage: 'images/vehicle-owners/bike/4.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹40/5km',
        vehicleType: 'bike',
        vehicleName: 'hero',
        vehicleImage: 'images/vehicles/bike/Hero_Passion_Plus.jpg',
        rating: 'images/ratings/rating-20.png'
    },
    {
        id: "8c9c52b5-5a19-4bcb-a5d1-158a74287c53",
        name: 'balvir',
        age: 20,
        ownerImage: 'images/vehicle-owners/bike/5.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹50/5km',
        vehicleType: 'bike',
        vehicleName: 'hero',
        vehicleImage: 'images/vehicles/bike/hero-hf-deluxe.jpg',
        rating: 'images/ratings/rating-30.png'
    },
    {
        id: "8c9c52b5-5a19-4bcb-a5d1-158a74287c53",
        name: 'kumar',
        age: 25,
        ownerImage: 'images/vehicle-owners/bike/6.jpg',
        experience: '3Years',
        contactDetails: +919876543211,
        estimatedCost: '₹60/5km',
        vehicleType: 'bike',
        vehicleName: 'hero',
        vehicleImage: 'images/vehicles/bike/hero-splendor-plus.jpg',
        rating: 'images/ratings/rating-50.png'
    },
    {
        id: "dd82ca78-a18b-4e2a-9250-31e67412f98d",
        name: 'ravan',
        age: 25,
        ownerImage: 'images/vehicle-owners/bike/7.jpg',
        experience: '2Years',
        contactDetails: +919876543211,
        estimatedCost: '₹30/5km',
        vehicleType: 'bike',
        vehicleName: 'Honda',
        vehicleImage: 'images/vehicles/bike/Honda Activa 6G.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "77919bbe-0e56-475b-adde-4f24dfed3a04",
        name: 'beem',
        age: 26,
        ownerImage: 'images/vehicle-owners/bike/8.jpg',
        experience: '2Years',
        contactDetails: +919876543211,
        estimatedCost: '₹35/5km',
        vehicleType: 'bike',
        vehicleName: 'Honda',
        vehicleImage: 'images/vehicles/bike/Honda Dio.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "3fdfe8d6-9a15-4979-b459-585b0d0545b9",
        name: 'arun',
        age: 22,
        ownerImage: 'images/vehicle-owners/bike/9.jpg',
        experience: '1Years',
        contactDetails: +919876543211,
        estimatedCost: '₹45/5km',
        vehicleType: 'bike',
        vehicleName: 'Honda',
        vehicleImage: 'images/vehicles/bike/honda-cd-110-dream.jpg',
        rating: 'images/ratings/rating-35.png'
    },
    {
        id: "58b4fc92-e98c-42aa-8c55-b6b79996769a",
        name: 'kumar',
        age: 26,
        ownerImage: 'images/vehicle-owners/bike/10.jpg',
        experience: '5Years',
        contactDetails: +919876543211,
        estimatedCost: '₹50/5km',
        vehicleType: 'bike',
        vehicleName: 'TVS',
        vehicleImage: 'images/vehicles/bike/jupiter.jpg',
        rating: 'images/ratings/rating-50.png'
    },
    {
        id: "5968897c-4d27-4872-89f6-5bcb052746d7",
        name: 'anil',
        age: 26,
        ownerImage: 'images/vehicle-owners/bike/11.jpg',
        experience: '5Years',
        contactDetails: +919876543211,
        estimatedCost: '₹30/5km',
        vehicleType: 'bike',
        vehicleName: 'honda',
        vehicleImage: 'images/vehicles/bike/honda-cd-110-dream.jpg',
        rating: 'images/ratings/rating-50.png'
    },
    {
        id: "aad29d11-ea98-41ee-9285-b916638cac4a",
        name: 'mohan',
        age: 27,
        ownerImage: 'images/vehicle-owners/bike/12.jpg',
        experience: '5Years',
        contactDetails: +919876543211,
        estimatedCost: '₹40/5km',
        vehicleType: 'bike',
        vehicleName: 'tvs',
        vehicleImage: 'images/vehicles/bike/tvs-sport.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "04701903-bc79-49c6-bc11-1af7e3651358",
        name: 'raju',
        age: 27,
        ownerImage: 'images/vehicle-owners/bike/13.jpg',
        experience: '2Years',
        contactDetails: +919876543211,
        estimatedCost: '₹40/5km',
        vehicleType: 'bike',
        vehicleName: 'Honda',
        vehicleImage: 'images/vehicles/bike/Honda Dio.jpg',
        rating: 'images/ratings/rating-50.png'
    },
];