export const medium = [
    {
        id: "86270236-921a-45a0-88fe-2d5741187b85",
        name: 'nayak',
        age: 60,
        ownerImage: 'images/vehicle-owners/medium/1.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹170/5km',
        vehicleType: 'medium',
        vehicleName: ' ashok leyland',
        vehicleImage: 'images/vehicles/medium/ashok-leyland-ecomet.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "be1bbac6-21fe-457c-8069-0eb5389f7089",
        name: 'raju',
        age: 57,
        ownerImage: 'images/vehicle-owners/medium/2.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹170/5km',
        vehicleType: 'medium',
        vehicleName: ' bharat-benz',
        vehicleImage: 'images/vehicles/medium/bharat-benz.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "6a4e8eef-9e68-45b7-a3a2-6ffe508d6fee",
        name: 'jagan',
        age: 27,
        ownerImage: 'images/vehicle-owners/medium/3.jpg',
        experience: '3 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹160/5km',
        vehicleType: 'medium',
        vehicleName: ' Tata',
        vehicleImage: 'images/vehicles/medium/tata signa.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "e1009a43-037e-4d67-a968-9d8ca84a3a82",
        name: 'madhu',
        age: 29,
        ownerImage: 'images/vehicle-owners/medium/4.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹150/5km',
        vehicleType: 'medium',
        vehicleName: ' Tata',
        vehicleImage: 'images/vehicles/medium/tata-t12-ultra.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "e1009a43-037e-4d67-a968-9d8ca84a3a82",
        name: 'ramayya',
        age: 59,
        ownerImage: 'images/vehicle-owners/medium/5.jpg',
        experience: '5 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹170/5km',
        vehicleType: 'medium',
        vehicleName: ' Tata',
        vehicleImage: 'images/vehicles/medium/tata-712-lpt.jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "4259668e-6d64-4478-bc3f-2c5210ae49e4",
        name: 'giri',
        age: 59,
        ownerImage: 'images/vehicle-owners/medium/6.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹170/5km',
        vehicleType: 'medium',
        vehicleName: ' swarag-mazda',
        vehicleImage: 'images/vehicles/medium/swaraj-mazda-samrat.jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "4afa2b2a-998c-477b-bbfb-3c2652e23337",
        name: 'ramu',
        age: 59,
        ownerImage: 'images/vehicle-owners/medium/9.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹150/5km',
        vehicleType: 'medium',
        vehicleName: ' Tata',
        vehicleImage: 'images/vehicles/medium/tata-t12-ultra.jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "c35d9a6f-184d-4ef3-9752-689256f7f571",
        name: 'gapi',
        age: 49,
        ownerImage: 'images/vehicle-owners/medium/17.jpg',
        experience: '1 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹150/5km',
        vehicleType: 'medium',
        vehicleName: ' eicher',
        vehicleImage: 'images/vehicles/medium/eicher-pro-2110 .jpg',
        rating: 'images/ratings/rating-45.png'
    },
];