export const small = [
    {
        id: "ee20210b-d4e2-4766-9eea-a87956bb774b",
        name: 'raghu',
        age: 43,
        ownerImage: 'images/vehicle-owners/small/1.jpg',
        experience: '3 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹80/5km',
        vehicleType: 'small',
        vehicleName: 'Ashok leyland',
        vehicleImage: 'images/vehicles/small/ashok leyland partner-6-tyre.jpg',
        rating: 'images/ratings/rating-35.png'
    },
    {
        id: "9be9ae60-a774-4721-b2cf-2f96f80d1a8b",
        name: 'suman',
        age: 53,
        ownerImage: 'images/vehicle-owners/small/2.jpg',
        experience: '5 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹90/5km',
        vehicleType: 'small',
        vehicleName: 'Ashok leyland',
        vehicleImage: 'images/vehicles/small/ashok-leyland-dost-strong.jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "7dffe3cb-c91b-45f6-bd46-03b61ee7246f",
        name: 'raju',
        age: 43,
        ownerImage: 'images/vehicle-owners/small/3.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹70/5km',
        vehicleType: 'small',
        vehicleName: 'Ashok leyland',
        vehicleImage: 'images/vehicles/small/ashok-leyland-dost.jpg',
        rating: 'images/ratings/rating-35.png'
    },
    {
        id: "1b6ac0af-ba47-4047-baa4-bd65d44462a7",
        name: 'raju',
        age: 56,
        ownerImage: 'images/vehicle-owners/small/4.jpg',
        experience: '5 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹100/5km',
        vehicleType: 'small',
        vehicleName: ' eicher',
        vehicleImage: 'images/vehicles/small/eicher-pro.jpg',
        rating: 'images/ratings/rating-50.png'
    },
    {
        id: "acb0e9a4-cb11-444d-9c34-5d1f64260070",
        name: 'naveen',
        age: 26,
        ownerImage: 'images/vehicle-owners/small/5.jpg',
        experience: '1 Year',
        contactDetails: +919876543211,
        estimatedCost: '₹50/5km',
        vehicleType: 'small',
        vehicleName: ' force',
        vehicleImage: 'images/vehicles/small/force-shaktiman.jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "2806a46e-63fa-4372-8538-15e46972181e",
        name: 'kumar',
        age: 46,
        ownerImage: 'images/vehicle-owners/small/6.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹79/5km',
        vehicleType: 'small',
        vehicleName: ' isuzu',
        vehicleImage: 'images/vehicles/small/isuzu D-max.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "34c0b8f0-fad8-418c-be20-e5c36a08cd1c",
        name: 'yadav',
        age: 50,
        ownerImage: 'images/vehicle-owners/small/7.jpg',
        experience: '4 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹86/5km',
        vehicleType: 'small',
        vehicleName: ' isuzu',
        vehicleImage: 'images/vehicles/small/isuzu sartaj.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "52cb3f59-23b9-4825-9668-0968a17904db",
        name: 'yadav',
        age: 50,
        ownerImage: 'images/vehicle-owners/small/7.jpg',
        experience: '4 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹80/5km',
        vehicleType: 'small',
        vehicleName: ' mahindra',
        vehicleImage: 'images/vehicles/small/mahindra furio-7.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "09591591-1a86-44fa-b84a-5d979b339ed5",
        name: 'vimal',
        age: 50,
        ownerImage: 'images/vehicle-owners/small/9.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹89/5km',
        vehicleType: 'small',
        vehicleName: ' mahindra',
        vehicleImage: 'images/vehicles/small/mahindra jayo.jpg',
        rating: 'images/ratings/rating-30.png'
    },
    {
        id: "ae8c4706-0028-4b6c-8c96-fde29ae137bc",
        name: 'raj',
        age: 30,
        ownerImage: 'images/vehicle-owners/small/10.jpg',
        experience: '3 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹69/5km',
        vehicleType: 'small',
        vehicleName: ' mahindra',
        vehicleImage: 'images/vehicles/small/mahindra supro.jpg',
        rating: 'images/ratings/rating-40.png'
    },
    {
        id: "b9d7be8e-94ba-4726-9a77-292737d6a9ad",
        name: 'aman',
        age: 50,
        ownerImage: 'images/vehicle-owners/small/11.jpg',
        experience: '3 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹75/5km',
        vehicleType: 'small',
        vehicleName: ' tata',
        vehicleImage: 'images/vehicles/small/tata 712-lpt.jpg',
        rating: 'images/ratings/rating-35.png'
    },
    {
        id: "b45d8f68-4625-41eb-82fb-7a7c7804e85c",
        name: 'kevin',
        age: 30,
        ownerImage: 'images/vehicle-owners/small/12.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹85/5km',
        vehicleType: 'small',
        vehicleName: ' tata',
        vehicleImage: 'images/vehicles/small/tata-intra-v20.jpg',
        rating: 'images/ratings/rating-35.png'
    },
    {
        id: "a893b5b2-a3bf-4d44-a2c7-e4fc14f4eee3",
        name: 'balu',
        age: 30,
        ownerImage: 'images/vehicle-owners/small/13.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹65/5km',
        vehicleType: 'small',
        vehicleName: ' tata',
        vehicleImage: 'images/vehicles/small/tata-intra-v30 .jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "850bc9ab-b46b-4fc1-8207-5f48c15ee2cd",
        name: 'guru',
        age: 60,
        ownerImage: 'images/vehicle-owners/small/14.jpg',
        experience: '5 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹100/5km',
        vehicleType: 'small',
        vehicleName: ' tata',
        vehicleImage: 'images/vehicles/small/tata-912.jpg',
        rating: 'images/ratings/rating-45.png'
    },
    {
        id: "c641847a-82d0-4201-b18c-629a6320f005",
        name: 'nayak',
        age: 60,
        ownerImage: 'images/vehicle-owners/small/17.jpg',
        experience: '2 Years',
        contactDetails: +919876543211,
        estimatedCost: '₹70/5km',
        vehicleType: 'small',
        vehicleName: ' ashok leyland',
        vehicleImage: 'images/vehicles/small/ashok-leyland-dost.jpg',
        rating: 'images/ratings/rating-40.png'
    },
]